---
name: Deploy Policy Assignment Exemptions

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/exemptions.yml
      - modules/exemptions/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/exemptions.yml
      - modules/exemptions/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: exemptions
  LOCATION: westeurope
  removeUnmanagedExemptions: 0

jobs:
  validate:
    name: Validate
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: What if deploy policy exemptions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Exemptions.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Location ${{ env.LOCATION }} -$removeUnmanagedExemptions ${{ env.removeUnmanagedExemptions }} -Verbose -WhatIf
          azPSVersion: latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - validate
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Exemptions.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Location ${{ env.LOCATION }} -$removeUnmanagedExemptions ${{ env.removeUnmanagedExemptions }} -Verbose
          azPSVersion: latest
