---
name: Deploy Policy Assignment Exemptions

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/exemptions.yml
      - modules/exemptions/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/exemptions.yml
      - modules/exemptions/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: exemptions
  LOCATION: westeurope
  removeUnmanagedExemptions: 'false'

jobs:
  validate_canary:
    name: Validate Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: What if deploy policy exemptions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Exemptions.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Location ${{ env.LOCATION }} -templateFile "${{ github.workspace }}/modules/shared/policyExemptions.bicep" -$removeUnmanagedExemptions "${{ env.removeUnmanagedExemptions }}"" -Verbose -WhatIf
          azPSVersion: latest

  validate_prod:
    name: Validate Prod
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: What if deploy policy exemptions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Exemptions.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Location ${{ env.LOCATION }} -templateFile "${{ github.workspace }}/modules/shared/policyExemptions.bicep" -$removeUnmanagedExemptions "${{ env.removeUnmanagedExemptions }}"" -Verbose -WhatIf
          azPSVersion: latest

  deploy_canary:
    name: Deploy Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    needs:
      - validate_canary
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Canary
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Exemptions.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Location ${{ env.LOCATION }} -templateFile "${{ github.workspace }}/modules/shared/policyExemptions.bicep" -$removeUnmanagedExemptions ${{ env.removeUnmanagedExemptions }} -Verbose
          azPSVersion: latest

  deploy_prod:
    name: Deploy Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    needs:
      - validate_prod
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Production
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Exemptions.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Location ${{ env.LOCATION }} -templateFile "${{ github.workspace }}/modules/shared/policyExemptions.bicep" -$removeUnmanagedExemptions ${{ env.removeUnmanagedExemptions }} -Verbose
          azPSVersion: latest
