---
name: Deploy Governance Rules

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - none
  # schedule:
  #  - cron: 0 0 * * sun #every sunday at 00.00
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: governance-rules

jobs:
  install-dependencies:
    name: Install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.ResourceGraph

  deploy_canary:
    name: Deploy Governance Rules Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: canary
      PREFIX: lz-canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: deploy governance rules
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-GovernanceRules.ps1 -Prefix ${{ env.PREFIX }}
          azPSVersion: latest

  deploy_prod:
    name: Deploy Governance Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ENVIRONMENT_SHORT_NAME: prod
      PREFIX: lz
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: deploy governance rules
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-GovernanceRules.ps1 -Prefix ${{ env.PREFIX }}
          azPSVersion: latest
