---
name: Deploy Platform Management Resources

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/management.yml
      - modules/management/*
      - environments/*/management*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/management.yml
      - modules/management/*
      - environments/*/management*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: management
  RESOURCE_GROUP_NAME: Management
  LOCATION: westeurope

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: e678d35b-125e-41ad-ae35-c04dfd4162e5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Build Bicep Templates
        run: |
          az bicep build --file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep

  validate_canary:
    name: Validate Canary
    runs-on: ubuntu-latest
    needs:
      - build
    if: success()
    env:
      ENVIRONMENT_SHORT_NAME: canary
      AZURE_SUBSCRIPTION_ID: e678d35b-125e-41ad-ae35-c04dfd4162e5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Validate
        run: |
          az deployment sub validate --name management --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.LOCATION }} --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

      - name: What-if
        run: |
          az deployment sub what-if --name management --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.LOCATION }} --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

  validate_prod:
    name: Validate Production
    runs-on: ubuntu-latest
    needs:
      - build
    if: success()
    env:
      ENVIRONMENT_SHORT_NAME: prod
      AZURE_SUBSCRIPTION_ID: 8228ddb9-d118-47b4-b4e7-1f1de7667d4d
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Validate
        run: |
          az deployment sub validate --name management --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.LOCATION }} --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

      - name: What-if
        run: |
          az deployment sub what-if --name management --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.LOCATION }} --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

  deploy_canary:
    name: Deploy Canary
    runs-on: ubuntu-latest
    needs:
      - validate_canary
      - validate_prod
    if: success() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
    environment:
      name: Canary
    env:
      ENVIRONMENT_SHORT_NAME: canary
      AZURE_SUBSCRIPTION_ID: e678d35b-125e-41ad-ae35-c04dfd4162e5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          az deployment sub create --name management --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.LOCATION }} --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

  deploy_prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs:
      - validate_canary
      - validate_prod
    if: success() && github.ref == 'refs/heads/main'
    environment:
      name: Production
    env:
      ENVIRONMENT_SHORT_NAME: prod
      AZURE_SUBSCRIPTION_ID: 8228ddb9-d118-47b4-b4e7-1f1de7667d4d
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          az deployment sub create --name management --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.LOCATION }} --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json
