---
name: Deploy Platform Management Resources

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/management.yml
      - modules/management/**
      - environments/*/management*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/management.yml
      - modules/management/**
      - environments/*/management*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: management
  RESOURCE_GROUP_NAME: Management
  LOCATION: westeurope

jobs:
  validate_canary:
    name: Validate Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}

      - name: Validate
        run: >
          az deployment mg validate
          --name management
          --management-group-id lz-canary
          --location ${{ env.LOCATION }}
          --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep
          --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

      - name: What-if
        run: >
          az deployment mg what-if
          --name management
          --management-group-id lz-canary
          --location ${{ env.LOCATION }}
          --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep
          --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

  validate_prod:
    name: Validate Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}

      - name: Validate
        run: >
          az deployment mg validate
          --name management
          --management-group-id lz
          --location ${{ env.LOCATION }}
          --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep
          --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

      - name: What-if
        run: >
          az deployment mg what-if
          --name management
          --management-group-id lz
          --location ${{ env.LOCATION }}
          --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep
          --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

  deploy_canary:
    name: Deploy Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    needs:
      - validate_canary
      - validate_prod
    if: success() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
    env:
      ENVIRONMENT_SHORT_NAME: canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}

      - name: Deploy
        run: >
          az deployment mg create
          --name management
          --management-group-id lz-canary
          --location ${{ env.LOCATION }}
          --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep
          --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json

  deploy_prod:
    name: Deploy Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    needs:
      - validate_canary
      - validate_prod
    if: success() && github.ref == 'refs/heads/main'
    env:
      ENVIRONMENT_SHORT_NAME: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}

      - name: Deploy
        run: >
          az deployment mg create
          --name management
          --management-group-id lz
          --location ${{ env.LOCATION }}
          --template-file ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/resources.bicep
          --parameters ${{ github.workspace }}/environments/${{ env.ENVIRONMENT_SHORT_NAME }}/${{ env.MODULE_NAME }}.parameters.json
