---
name: Deploy Policies

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/policies.yml
      - modules/policies/**
      - environments/*/policies*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/policies.yml
      - modules/policies/**
      - environments/*/policies*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: policies
  LOCATION: westeurope

jobs:
  validate_canary:
    name: Validate Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: canary
      PREFIX: lz-canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Compare policies, initiatives, and assignments
        id: compare-policies
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Compare-Policy.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Prefix ${{ env.PREFIX }}
          azPSVersion: latest

      - name: Fail on delete detected if build reason is pull request
        run: |
          echo "::error::Delete detected. Manual intervention required."
          exit 1
        if: steps.compare-policies.outputs.DELETE_DETECTED && github.event_name == 'pull_request'

      - name: What if deploy policy definitions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyDefinition.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/definitions" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose -WhatIf
          azPSVersion: latest

      - name: What if deploy policy set definitions (initiatives)
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Initiative.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/initiatives" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose -WhatIf
          azPSVersion: latest

      - name: What if deploy policies, initiatives, and assignments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyAssignment.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/assignments" -Location ${{ env.LOCATION }} -Prefix ${{ env.PREFIX }} -Environment ${{ env.ENVIRONMENT_SHORT_NAME }} -Verbose -WhatIf
          azPSVersion: latest

  validate_prod:
    name: Validate Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: prod
      PREFIX: lz
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Compare policies, initiatives, and assignments
        id: compare-policies
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Compare-Policy.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -Prefix ${{ env.PREFIX }}
          azPSVersion: latest

      - name: Fail on delete detected if branch is main
        run: |
          echo "::error::Delete detected. Manual intervention required."
          exit 1
        if: steps.compare-policies.outputs.DELETE_DETECTED && github.ref == 'refs/heads/main'

      - name: What if deploy policy definitions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyDefinition.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/definitions" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose -WhatIf
          azPSVersion: latest

      - name: What if deploy policy set definitions (initiatives)
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Initiative.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/initiatives" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose -WhatIf
          azPSVersion: latest

      - name: What if deploy policies, initiatives, and assignments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyAssignment.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/assignments" -Location ${{ env.LOCATION }} -Prefix ${{ env.PREFIX }} -Environment ${{ env.ENVIRONMENT_SHORT_NAME }} -Verbose -WhatIf
          azPSVersion: latest

  deploy_canary:
    name: Deploy Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    needs:
      - validate_canary
      - validate_prod
    if: success() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
    env:
      ENVIRONMENT_SHORT_NAME: canary
      PREFIX: lz-canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy policy definitions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyDefinition.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/definitions" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose
          azPSVersion: latest

      - name: Deploy policy set definitions (initiatives)
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Initiative.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/initiatives" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }}} -Verbose
          azPSVersion: latest

      - name: Deploy policies, initiatives, and assignments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyAssignment.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/assignments" -Location ${{ env.LOCATION }} -Prefix ${{ env.PREFIX }} -Environment ${{ env.ENVIRONMENT_SHORT_NAME }} -Verbose
          azPSVersion: latest

  deploy_prod:
    name: Deploy Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    needs:
      - validate_canary
      - validate_prod
    if: success() && github.ref == 'refs/heads/main'
    env:
      ENVIRONMENT_SHORT_NAME: prod
      PREFIX: lz
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy policy definitions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyDefinition.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/definitions" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose
          azPSVersion: latest

      - name: Deploy policy set definitions (initiatives)
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-Initiative.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/initiatives" -Location ${{ env.LOCATION }} -ManagementGroupId ${{ env.PREFIX }} -Verbose
          azPSVersion: latest

      - name: Deploy policies, initiatives, and assignments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Deploy-PolicyAssignment.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/assignments" -Location ${{ env.LOCATION }} -Prefix ${{ env.PREFIX }} -Environment ${{ env.ENVIRONMENT_SHORT_NAME }} -Verbose
          azPSVersion: latest
